### ISSUE TITLE
Add CSS3 for Mobile Devices

### ISSUE THREAD

**Issue by lucasvenez** [deeplibras/deeplibras.github.io#1]
It is required to include a CSS3 script to mobile devices. Checkout the page [here](https://www.smashingmagazine.com/2010/07/how-to-use-css3-media-queries-to-create-a-mobile-version-of-your-website/).

**Comment by Pliavi** [comment]
The page is already almost fully adaptive (the components relocates as necessary), it's only necessary to add the viewport meta-tag.

The most of it's parts don't need to be changed by media-queries (only if it's needed to make a big position change), top menu and contact panel are the unique problems seen:
- **Contact panel:** Devices with less than ±420px width may expand the screen to show this panel completely, because it have a min-width property on css with 400px and 10px padding, it can be changed to a % value, but how who set this value thought, the email will be break to another line. So with media-queries or not, this will happen, and I think shrinking the font is not an alternative.
- **Top Navbar:** Now media-queries are necessary, these 3 buttons may fit in all currently devices  and the bar is already thin, but would be nice to see then centered when the device is getting smaller, and it's just can be done with media-queries (how the page linked). And other thing is the country/language flags, they can be throw below the menu. Or how the most other sites, make a cascade menu that are just shown when the device get an specific size.

I had illustrated it, but the proxy isn't permiting me to attach the image.

**Comment by rodrigobriet** [comment]
The new version solved the problems on mobile devices. If you find some problem, please open a new issue.
